### PR TITLE
codemill-id-56e9b9bea7e2c103005db942 fixes #10

### LINKED ISSUE #10: Use Angular UI Router
The purpose of this feature is to handle the routing via Angular UI instead of Express. This will avoid the white flashes when switching pages.

## Views

  - [x] Set up a unique template that the 6 views will use
    - The views are `/index`, `/locations`, `/services`, `/contact`, `/about` and `/legal`
  - [x] The SEO (Title, description and keywords) is different according to the pages

## Navigation

  - [x] The left navigation should be in a dedicated partial
  - [x] Each item on the navigation have an active state
    - `/index`: Do nothing
    - `/locations`: Add a class `active` to the locations item
    - `/services `: Add a class `active` to the services item
    - `/contact `: Add a class `active` to the contact item
    - `/about `: Add a class `active` to the about item
    - `/index`: Do nothing

screen shot 2016-03-16 at 8 20 55 am

## Locations

  - [x] The Google Maps JS snippet should be called by Angular in a directive only on the `/locations` page.

---

For details on how the views looks like you take a look at the product specifications: https://github.com/lanceplaine/capnet-pressing-design/tree/master/markdown

### PR DESCRIPTION
**Pull request by acoshift**
codemill-id-56e9b9bea7e2c103005db942 fixes #10

### CODE REVIEW

**Comment by lanceplaine** [comment]
Thank you for your PR @acoshift :)
I will take a look at it today and should be able to go back to you this week.

**Comment by acoshift** [comment]
You can also remove express routes (about, contact, legal, locations, services) and fallback 404 to index.html, but 404 will redirect to "/" or add a route to handle 404 on angular app.

**Comment by lanceplaine** [comment]
Hi @acoshift,

I reviewed your PR and it helped me with my code. I'm not going to merge your PR for multiple reasons, one being the fact that you wrote in `public` instead of `src` (I'm going to add this information to the `CONTRIBUTING.md` file for next time) but I still plan to reward you. I will ask the CodeMill support to mark the task as completed. I will update you as soon as I have an answer.

Feel free to take a look at the PR I merged https://github.com/lanceplaine/capnet-pressing/pull/41

Let me know if you have any questions

**Comment by lanceplaine** [comment]
https://gitter.im/CodeMillApp/support

**Comment by lanceplaine** [comment]
@acoshift: They approved the payment.

Have a great day

**Comment by acoshift** [comment]
Thanks for the reward.
And sorry about code in public folder, I just see that there are scripts in src/scripts/modules.
I'm glad that my code can help you. ^^

**Pull request closed without merging**
